version: '3:7'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5676:5672
      - 15676:15672
    env_file:
      - .env
    networks:
      - my-app


  postgres-users:
    image: postgres:latest
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URI_USERS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-app

  postgres-tournaments:
    image: postgres:latest
    ports:
      - 5437:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URI_TOURNAMENTS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-app

  api-gateway:
    build:
      context: ./api-gateway  # путь к папке с Dockerfile API Gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - my-app

  tournament-service:
    build:
      context: ./tournament-service  # путь к папке с Dockerfile
      dockerfile: Dockerfile
    command: ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
    ports:
      - "3001:3000"  # внешний порт:внутренний порт
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres-tournaments
      - api-gateway
    networks:
      - my-app

  user-service:
    build:
      context: ./user-service  # путь к папке с Dockerfile
      dockerfile: Dockerfile
    command: [ "sh", "-c", "npx prisma migrate deploy && npm run start:prod" ]
    ports:
      - "3002:3000"  # внешний порт:внутренний порт
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres-tournaments
      - api-gateway
    networks:
      - my-app

  duel-service:
    build:
      context: ./duel-service  # путь к папке с Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3003:3000"  # внешний порт:внутренний порт
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres-tournaments
      - api-gateway
    networks:
      - my-app


volumes:
  postgres_data:
networks:
  my-app: